### PR TITLE
Improve render and allow simple list render in a single line

### LINKED ISSUE #236: Render format with formatted HOCON
Hi,

I find that in formatted HOCON, entry is rendered like ```key=value```(if value is not an object) or ```key value```(if value is an object). I think for better readability, why not use ```key = value```? The string generated might be prettier in this format.

Thanks!

### PR DESCRIPTION
**Pull request by acaly**
I have tried to make the implementation clean and easier to understand. Fix #236.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @acaly,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by acaly** [comment]
OK I think this might not be what this library should do. I am planning to implement custom renderers in my own project. It's a pity I can not rely on the ```render``` function.

**Comment by boformer** [comment]
Why did you close this? 
This is really useful.
I would maybe add one or two render options to make the features optional.

**Comment by acaly** [comment]
I closed this thread as we chose to implement it in our own project using config library. Anyway, it may not be a core feature this library needs to have. If the feature is really useful to others, I am certainly glade to see it merged, maybe after some modifications though.

**Pull request closed without merging**
