### PR TITLE
issue #405 fixed: config loading strategy implemented

### PR DESCRIPTION
**Pull request by pshirshov**

### CODE REVIEW

**Comment by havocp** [comment]
CI failure looks like missing doc comments. "sbt doc" to test locally I think

**Comment by havocp** [comment]
Looks good! Two things could use fixing up I think.

1) It looks like your editor added a lot of noise to the commit (braces and whitespace), maybe you could fix that by manually re-applying the substantive changes to a clean copy of the file using a simpler editor (or with auto formatting disabled in your editor). It looks like this would be adding a method and removing one, fairly straightforward.

2) there should be some sort of test(s) showing that we in fact use a custom strategy when it is provided. If you look at ConfigImpl and some of the existing tests you can maybe see how we've tested system variables in the past (the trick is allowing them to be reloaded). Or the easiest might be to simply not cache the strategy, since we cache the Config itself anyway, always looking up the system prop each time we are rebuilding the Config is probably fine. There's already a mechanism to invalidate the cached Config that could be used in tests.

**Comment by FeiWongReed** [comment]
Ok, I've added docs and test.

**Comment by havocp** [comment]
One minor comment. Looking good to me. Thank you!

**Comment by FeiWongReed** [comment]
Fixed...

**Comment by havocp** [comment]
thanks very much :-)

**Comment by pshirshov** [comment]
You are welcome. Thanks.

**Pull request merged**
