### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @valery1707,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by valery1707** [comment]
I already sign Typesafe Contributors License Agreement

**Comment by havocp** [comment]
Thanks for the contribution - the README already links to our javadoc though?
http://typesafehub.github.com/config/latest/api/ is the canonical location...

**Comment by valery1707** [comment]
I think that color badge with version in top of page is more attractive than simple link in middle of page.
Now i changed link in badge to canonical location.

**Comment by valery1707** [comment]
Commit is pushed to my branch but github is not add it to this pull request :(

**Comment by 2m** [comment]
There is already a badge with the latest version on top of the readme. And `javadoc-emblem.rhcloud.com` seems to return 503. Therefore I am going to close this.

**Pull request closed without merging**
