### PR TITLE
Add ConfigBeanFactory

### PR DESCRIPTION
**Pull request by havocp**

### CODE REVIEW

**Comment by benmccann** [comment]
This is awesome!! Thanks @havocp and @zstd!  The code looks good to me!

**Comment by typesafehub-validator** [comment]
Hi @zstd,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by havocp** [comment]
yikes, where has that cla validator been hanging out? @zstd I hope it's ok to click through there. don't know why it didn't post before, I assumed that meant you'd already signed.

**Comment by typesafehub-validator** [comment]
Hi @zstd,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by havocp** [comment]
Made a few more changes, rationales in the individual commit messages. I think that's everything I wanted to do with this before merging it. But anyone who would like to have a look and find bugs/suggestions, please do.

Otherwise just waiting on the CLA to merge. Thanks @zstd and @benmccann!

**Comment by zstd** [comment]
Accepted the CLA.

**Comment by benmccann** [comment]
Confirmed. Thanks @zstd !  http://typesafe.com/contribute/cla/check/zstd

@havocp the code all looks good to me. Thanks again for the help on this!!

**Comment by havocp** [comment]
I noticed that we'd lost @benmccann from the commit history so I rebased to show his original version of BeanFactory and then subsequent changes. Merging now.

**Comment by benmccann** [comment]
Thanks @havocp !!  I can't wait for a new release with this feature :-)

**Pull request merged**
