### PR TITLE
SerializedConfigValue.writeExternal and readExternal are inconsistent

### PR DESCRIPTION
**Pull request by akornev**
See https://github.com/typesafehub/config/issues/461 for details.

### CODE REVIEW

**Comment by akornev** [comment]
Thanks for your reviewing my PR! 

Wrt your first question, I'm not quite sure I understand what type of unit test you have in mind. Could you please elaborate?

As for your second question, the answer is "No, I don't think so". In fact, `skipField()` is altogether redundant in `SerializedConfigValue.readExternal(ObjectInput)`. If you look carefully at 
`SerializedConfigValue.writeExternal(ObjectOutput)`, you'll see that it only ever writes 2 fields: `SerializedField.ROOT_VALUE` and `SerializedField.ROOT_WAS_CONFIG`, as well as `SerializedField.END_MARKER`. It basically means that the corresponding `SerializedConfigValue.readExternal(ObjectInput)` will only ever have to read the two fields followed by the end marker. There is simply no way there will be any "unknown" fields in the input stream.

Finally, please note that only the **top-level** object's `SerializedConfigValue.readExternal(ObjectInput)/writeExternal(ObjectOutput)` are invoked by the serialization framework. Once inside, the rest of the Config hierarchy (de)serialization is entirely handled by `SerializedConfigValue.readValue()/writeValue()`, and `readExternal()/writeExternal()` are never called again. This is the reason why `fieldIn()` is only required in the top level `readExternal()`.

I've updated the PR with a slightly simplified version of `readExternal()` that no longer calls `skipField()`.

Please review. Thanks!

**Comment by akornev** [comment]
Hello! Is there any chance this PR will be reviewed and hopefully merged any time soon? This is about to become a showstopper for me. 
Thanks!

**Comment by havocp** [comment]
Hi, I will do my best, not at a computer right this second and always swamped!

I would feel better about this if we had a test (see the current test suite for a lot of example tests covering this file already) which would break if someone regressed this again. Otherwise I would not be shocked to see it regress again ...

**Comment by akornev** [comment]
I definitely see your point, but implementing such test would require an external serializer library (in this case it would be Apache Ignite) as a dependency. I'm not sure if it's ok, but if you feel it's worth the trouble, then I'd gladly do it. Cheers!

**Comment by havocp** [comment]
No, let's not do anything over the top. I haven't read the docs about how to override the serializer but was hoping it could be done in toy form for the scope of a test or two.

**Comment by havocp** [comment]
@2m @patriknw or others, do you want to look this over? inclined to merge soon

**Comment by akornev** [comment]
@havocp Added a small unit test that demonstrates the fix. The test fails if run against the original code in `com.typesafe.config.impl.SerializedConfigValue`. Please let me know if you have any questions. Thanks!

**Comment by havocp** [comment]
Thanks for tracking down this issue and for the PR. Apologies for my slowness!

**Pull request merged**
