### PR TITLE
make sure expressions like .33 can be parsed as doubles

### PR DESCRIPTION
**Pull request by tkaiser**
issue #361

### CODE REVIEW

**Comment by havocp** [comment]
Thanks! If you haven't, could you click through the cla here with your github account?
https://www.typesafe.com/contribute/cla

Would it be useful to also test the type `.33` is "natively" parsed as? That is, `getValue().valueType() == ConfigValueType.FLOAT` or whatever (I'm not actually sure if it's float or string right now, but it'd be nice to test so we don't change it accidentally)

**Comment by tkaiser** [comment]
I did sign the CLA yesterday, let me know if anything went wrong there.

Yeah you're probably right, as ```.33``` is parsed as an unquoted string and only coerced into a double when requested. I'll check it out, might take me a bit to get to it though.

**Comment by tkaiser** [comment]
anything open here? from my side the PR is ready to

**Comment by havocp** [comment]
Apologies, GitHub does not send a notification when commits are added to a PR, only if you comment.

I was only suggesting testing the current behavior rather than changing it (changing it could break someone without much corresponding benefit I would think?). Just thinking the tests should ensure we notice if it changes accidentally.

**Comment by tkaiser** [comment]
oh, gotcha. changed it back

**Comment by havocp** [comment]
awesome, thanks!

**Pull request merged**
