### PR TITLE
Sort keys alphanumerically.

### PR DESCRIPTION
**Pull request by derrickburns**
Addresses #228.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @derrickburns,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by typesafehub-validator** [comment]
Hi @derrickburns,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by havocp** [comment]
Thanks!

We have some extra things mixed in here - I think this PR should be the first commit only.

Unfortunately that first commit has a problem that it pulls in LGPL code, which would LGPL-ify the entire codebase by association. The Scala/Akka/Play stack has a rule that it does not have any (L)GPL dependencies. So we need a different implementation of that sort algorithm (and it cannot be based on or derived from the LGPL one, it needs to be a fresh from scratch implementation).

I think it might be possible to cheat somehow. For example, what if we took all the numeric keys and prefixed them with `0` padding to make them all the same length, so we would be sorting `"01", "02", "03"` etc., and then post-sort we strip the 0's back off? Obviously we'd only want to do this if the keys were all numeric and didn't already start with 0. But it would allow us to use the regular default string sort and still get things in the right order perhaps.

**Comment by derrickburns** [comment]
What about this implementation:

https://github.com/sawano/alphanumeric-comparator

**Comment by derrickburns** [comment]
I replaced the Comparator implementation with an Apache 2.0 licensed one.

This pull request also addresses #230.

**Comment by typesafehub-validator** [comment]
Hi @derrickburns,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by derrickburns** [comment]
I added code that is called when parseMap is used. This code will detect when maps actually encode arrays and to representing them as SimpleConfigLists instead of SimpleConfigObjects.  This lessens the need to sort map keys alphanumerically, although this is still a nice feature.

**Pull request closed without merging**
