### PR TITLE
#495 Add Support For Set Types In Config Beans

### PR DESCRIPTION
**Pull request by karthicks**
This pull request addresses the following issue: https://github.com/typesafehub/config/issues/495

### CODE REVIEW

**Comment by havocp** [comment]
Thanks! Looks generally good. Something isn't passing CI, needs investigation.

**Comment by karthicks** [comment]
@havocp , resolved the build issue, sorry about that. Please take another look when you get a chance, thanks!

**Comment by havocp** [comment]
Thanks!

**Comment by ktoso** [comment]
cool idea, thanks :)

**Pull request merged**
